// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3kWh9jpuNqjf236ymP-Y1iklVB3B3aSs',
    appId: '1:680178619923:web:794421b3f89f4a3d1a11e6',
    messagingSenderId: '680178619923',
    projectId: 'base-app-3d7dc',
    authDomain: 'base-app-3d7dc.firebaseapp.com',
    storageBucket: 'base-app-3d7dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_TxWX12gmYgIpDJA34xGhKvBHZfDZNZA',
    appId: '1:680178619923:android:c0472af4d41865671a11e6',
    messagingSenderId: '680178619923',
    projectId: 'base-app-3d7dc',
    storageBucket: 'base-app-3d7dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRd1CtQg2rfhwNTqcbEEWsMuO7LhfVx2I',
    appId: '1:680178619923:ios:f41eba4e9082cd611a11e6',
    messagingSenderId: '680178619923',
    projectId: 'base-app-3d7dc',
    storageBucket: 'base-app-3d7dc.appspot.com',
    iosClientId: '680178619923-73kinls7bbd98lvgcoijs43rhbv3jid6.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRd1CtQg2rfhwNTqcbEEWsMuO7LhfVx2I',
    appId: '1:680178619923:ios:acf89087ecfe8fb81a11e6',
    messagingSenderId: '680178619923',
    projectId: 'base-app-3d7dc',
    storageBucket: 'base-app-3d7dc.appspot.com',
    iosClientId: '680178619923-568l6je0155u9n5d49qiac81umt7ji8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseApp.RunnerTests',
  );
}
